[mypy]
ignore_missing_imports = True

# Archivos ruidosos que NO bloquean reproducibilidad
[mypy-infer_lstm]
disable_error_code = assignment,operator,misc,index

[mypy-evaluar_robustez_hybrid]
disable_error_code = misc,union-attr